title: Rupali's Portfolio
description: >-
  Rupali Wadhawan is a Business and Data Scientist living in Toronto, ON,
  Canada.
social_media_share_image: /uploads/1697526354080-2.jpeg
disqus-identifier:
google-analytics:
